image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate sphinx-doc

pages:
  script:
  - mkdir -p docs
  - make clean
  - make html
  - cp -r build/html/* docs/.
  artifacts:
    paths:
      - public
